import os
from pathlib import Path
from datetime import datetime
import logging

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger("BusinessAudit")

class BusinessAudit:
    def __init__(self, vault_path: str):
        self.vault_path = Path(vault_path)
        self.goals_file = self.vault_path / "Business_Goals.md"
        self.dashboard_file = self.vault_path / "Dashboard.md"
        self.reports_dir = self.vault_path / "Reports"
        self.accounting_dir = self.vault_path / "Accounting"

    def run_audit(self):
        logger.info("Starting Business Audit...")
        
        # 1. Read Goals
        goals_content = self.goals_file.read_text(encoding='utf-8') if self.goals_file.exists() else "No goals file found."
        
        # 2. Read Dashboard Activity
        dashboard_content = self.dashboard_file.read_text(encoding='utf-8') if self.dashboard_file.exists() else "No dashboard file found."
        
        # 3. Simple Financial Check (Scan Accounting folder)
        total_revenue = 0
        total_costs = 0
        if self.accounting_dir.exists():
            for file in self.accounting_dir.glob("*.md"):
                content = file.read_text(encoding='utf-8')
                lower_content = content.lower()
                
                # Extract amount
                amount = 0
                for line in content.splitlines():
                    if "amount:" in line.lower():
                        try:
                            amount = float(line.split(":")[1].strip().replace("$", "").replace(",", ""))
                            break
                        except:
                            pass
                
                # Distinguish between revenue and cost
                if "type: software_cost" in lower_content or "software" in lower_content:
                    total_costs += amount
                else:
                    total_revenue += amount

        # 4. Generate Report
        report_date = datetime.now().strftime("%Y-%m-%d")
        report_filename = f"Business_Audit_{report_date}.md"
        report_path = self.reports_dir / report_filename
        
        report_content = f"""# 📈 Business Audit Report - {report_date}

## 🎯 Progress Against Goals
- **Monthly Revenue Target**: $5,000
- **Current MTD Revenue**: ${total_revenue:,.2f}
- **Target Reach %**: {(total_revenue/5000)*100:.1f}%

## 📝 Recent System Activity
(Extracted from Dashboard)
{self._extract_recent_activity(dashboard_content)}

## 🕵️ Subscription Audit Rules
- [ ] No login in 30 days? (Check logs)
- [ ] Cost increased > 20%? (Check invoices)
- [ ] Duplicate functionality? (Review Handbook)

---
*Generated by Digital FTE (Phase 3 - Gold Tier)*
"""
        report_path.write_text(report_content, encoding='utf-8')
        logger.info(f"Audit report generated: {report_path}")
        
        # 5. Update Dashboard.md Metrics
        self._update_dashboard(total_revenue, total_costs)
        
        return report_path

    def _update_dashboard(self, total_revenue, total_costs):
        """Inject the latest revenue and metrics into Dashboard.md."""
        if not self.dashboard_file.exists():
            return
            
        content = self.dashboard_file.read_text(encoding='utf-8')
        
        # Update Revenue
        revenue_line = f"- **Current MTD Revenue**: ${total_revenue:,.2f}"
        target_reach = (total_revenue / 5000) * 100
        reach_line = f"- **Target Reach %**: {target_reach:.1f}%"
        
        # Update KPI Costs
        cost_status = f"${total_costs:,.2f}"
        
        # Replace placeholders using re
        import re
        content = re.sub(r"- \*\*Current MTD Revenue\*\*: .*", revenue_line, content)
        content = re.sub(r"- \*\*Target Reach %\*\*: .*", reach_line, content)
        
        # Update Software Costs in table
        content = re.sub(r"\| Software Costs \| .* \| < \$200 \|", f"| Software Costs | {cost_status} | < $200 |", content)
        
        self.dashboard_file.write_text(content, encoding='utf-8')
        logger.info("Updated Dashboard.md with latest financial metrics and KPIs.")

    def _extract_recent_activity(self, content):
        lines = content.splitlines()
        activity = []
        found_recent = False
        for line in lines:
            if "Recent Activity" in line: # Partial match for emoji headers
                found_recent = True
                continue
            if found_recent and line.strip().startswith("-"):
                activity.append(line)
            if found_recent and line.strip().startswith("#") and "Recent Activity" not in line: # Stop at next section
                break
        return "\n".join(activity[-10:]) if activity else "No recent activity found."

if __name__ == "__main__":
    VAULT_DIR = r"c:\Users\Rawish\Desktop\Hackathon_0"
    audit = BusinessAudit(VAULT_DIR)
    audit.run_audit()
